/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmilpsession_free: (a: number, b: number) => void;
export const aggregate_pile_options: (a: any) => [number, number, number];
export const apply_load_point_group_assignment: (a: any) => [number, number, number];
export const apply_load_point_group_edit: (a: any) => [number, number, number];
export const assess_load_point_group_assignments: (a: any) => [number, number, number];
export const assess_technical_assignment: (a: any) => [number, number, number];
export const build_load_point_topology: (a: any) => [number, number, number];
export const build_tip_level_region_topology: (a: any) => [number, number, number];
export const calculate_pile_option_analysis: (a: any) => [number, number, number];
export const calculate_pile_option_cost: (a: any) => [number, number, number];
export const choose_default_options: (a: any) => [number, number, number];
export const derive_load_point_groups: (a: any) => [number, number, number];
export const export_pile_plan_csv: (a: any) => [number, number, number, number];
export const export_pile_plan_xlsx: (a: any) => [number, number, number, number];
export const import_project_from_files: (a: any) => [number, number, number];
export const preview_import_file: (a: any) => [number, number, number];
export const preview_load_point_group_edit: (a: any) => [number, number, number];
export const preview_pile_plan_import_file: (a: any) => [number, number, number];
export const read_project_document: (a: any) => [number, number, number];
export const refresh_project_from_files: (a: any) => [number, number, number];
export const wasmilpsession_new: () => number;
export const wasmilpsession_run: (a: number, b: any, c: any, d: any) => [number, number, number];
export const write_project_document: (a: any) => [number, number, number, number];
export const wasm_bindgen_df0aded92f0742a8___convert__closures_____invoke___wasm_bindgen_df0aded92f0742a8___JsValue______true_: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
