import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { canonicalProjectForTest, projectTipLevelKeysForTest } from "../../core/projectTestSupport.ts";
import { createInitialProjectState } from "../../domain/project/projectState.ts";
import { createMcpProjectFileOperations } from "./projectFileOperations.ts";

const project = canonicalProjectForTest(readFileSync("../../sample_project/sample_project.ifcpp", "utf8"));
const state = createInitialProjectState(project, { initializeDefaultPiles: false }, projectTipLevelKeysForTest(project));
const marker = { project_instance_id: "project", project_revision: 1 };
function setup(cancel = false, staleDuringRead = false,
  overrides: NonNullable<Parameters<typeof createMcpProjectFileOperations>[1]> = {}) {
  let current = { ...marker }, installs = 0, saves = 0, reads = 0;
  const operations = createMcpProjectFileOperations({
    currentState: () => state, currentMarker: () => current, currentPath: () => "project.ifcpp",
    canEdit: () => true, confirmReplacement: async () => !cancel,
    installOpened: () => { installs++; }, didSave: () => { saves++; },
  }, {
    chooseOpen: async () => "project.ifcpp", readFile: async () => {
      reads++;
      if (staleDuringRead) current = { ...current, project_revision: 2 };
      return "contents";
    },
    readDocument: async () => ({ status: "valid", project, keys: projectTipLevelKeysForTest(project) }),
    serialize: async () => "contents", writeFile: async () => {},
    ...overrides,
  });
  return { operations, counts: () => ({ installs, saves, reads }) };
}
test("opening installs a validated project exactly once", async () => {
  const context = setup();
  const result = await context.operations.run({ kind: "open" }, marker, () => true);
  assert.equal(result.status, "completed");
  assert.equal(context.counts().installs, 1);
});
test("cancelling replacement does not read or install a file", async () => {
  const context = setup(true);
  assert.equal((await context.operations.run({ kind: "open" }, marker, () => true)).status, "cancelled");
  assert.deepEqual(context.counts(), { installs: 0, saves: 0, reads: 0 });
});
test("a stale project during file read is never installed", async () => {
  const context = setup(false, true);
  const result = await context.operations.run({ kind: "open" }, marker, () => true);
  assert.equal(result.status, "failed");
  assert.equal(context.counts().installs, 0);
});
test("saving reports the saved file through the session callback", async () => {
  const context = setup();
  assert.equal((await context.operations.run({ kind: "save" }, marker, () => true)).status, "completed");
  assert.equal(context.counts().saves, 1);
});

test("export passes generated bytes and the explicit plan name to the file dialog", async () => {
  const plan = state.pilePlans[0];
  const bytes = new Uint8Array([1, 2, 3]);
  let writes = 0;
  const context = setup(false, false, {
    exportCsv: async () => bytes,
    chooseExport: async (name, format) => {
      assert.ok(name.endsWith(".csv"));
      assert.equal(format, "csv");
      return "plan.csv";
    },
    writeExport: async (path, contents) => {
      assert.equal(path, "plan.csv");
      assert.equal(contents, bytes);
      writes++;
    },
  });
  const result = await context.operations.run({ kind: "export", planId: plan.id, format: "csv" }, marker, () => true);
  assert.equal(result.status, "completed");
  assert.equal(writes, 1);
});

test("an unknown export plan is rejected before opening a dialog", async () => {
  const context = setup(false, false, { chooseExport: async () => { throw new Error("unexpected dialog"); } });
  const result = await context.operations.run({ kind: "export", planId: "unknown", format: "xlsx" }, marker, () => true);
  assert.equal(result.status, "failed");
  if (result.status === "failed") assert.equal(result.code, "unknown_plan");
});
